"""Phase 4 research candidates. None is activated or claimed live-verified."""

CANDIDATES = [
    {
        "name": "KwaZulu-Natal Provincial Treasury Tenders",
        "slug": "kzn-provincial-treasury",
        "source_type": "PROVINCIAL",
        "organisation": "KwaZulu-Natal Provincial Treasury",
        "website_url": "https://www.kzntreasury.gov.za/",
        "procurement_url": "https://www.kzntreasury.gov.za/Pages/Tenders.aspx",
        "mechanism": "HTML",
        "why": "Provincial coverage and official procurement page",
        "access": "Public page; live structure not verified from this environment",
    },
    {
        "name": "eThekwini Municipality Procurement",
        "slug": "ethekwini-municipality",
        "source_type": "MUNICIPAL",
        "organisation": "eThekwini Metropolitan Municipality",
        "website_url": "https://www.durban.gov.za/",
        "procurement_url": "https://www.durban.gov.za/pages/business/procurement",
        "mechanism": "HTML",
        "why": "Metropolitan municipal coverage",
        "access": "Public page; live structure not verified from this environment",
    },
    {
        "name": "Msunduzi Municipality Tenders",
        "slug": "msunduzi-municipality",
        "source_type": "MUNICIPAL",
        "organisation": "The Msunduzi Municipality",
        "website_url": "https://www.msunduzi.gov.za/",
        "procurement_url": "https://www.msunduzi.gov.za/site/tenders/",
        "mechanism": "HTML",
        "why": "Local municipality and geography-alias coverage",
        "access": "Public page; live structure not verified from this environment",
    },
    {
        "name": "Eskom Tender Bulletin",
        "slug": "eskom-tender-bulletin",
        "source_type": "SOE",
        "organisation": "Eskom Holdings SOC Ltd",
        "website_url": "https://www.eskom.co.za/",
        "procurement_url": "https://tenderbulletin.eskom.co.za/",
        "mechanism": "JAVASCRIPT_APPLICATION",
        "why": "SOE source and application-style listing diversity",
        "access": "Public endpoint; live access/terms require verification",
    },
    {
        "name": "SANRAL Tenders",
        "slug": "sanral-tenders",
        "source_type": "PUBLIC_ENTITY",
        "organisation": "South African National Roads Agency SOC Ltd",
        "website_url": "https://www.nra.co.za/",
        "procurement_url": "https://www.nra.co.za/sanral-tenders/",
        "mechanism": "HTML_DOCUMENT_REPOSITORY",
        "why": "Public entity and document-oriented procurement diversity",
        "access": "Public page; live structure not verified from this environment",
    },
]
DECISIONS = {
    "kzn-provincial-treasury": "SOURCE_NOT_FOUND",
    "ethekwini-municipality": "LIVE_CONNECTOR_FEASIBLE",
    "msunduzi-municipality": "REQUIRES_MANUAL_CONFIGURATION",
    "eskom-tender-bulletin": "LIVE_CONNECTOR_FEASIBLE",
    "sanral-tenders": "ACCESS_RESTRICTED",
}
