package za.co.tenderhub.ui.screens
import android.Manifest
import android.os.Build
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import za.co.tenderhub.domain.model.*
@Composable fun NotificationCenterScreen(state:DataState<List<TenderNotification>>,onRetry:()->Unit,onRead:(TenderNotification)->Unit,onReadAll:()->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Notifications",style=MaterialTheme.typography.headlineMedium);TextButton(onReadAll){Text("Mark all read")}};when(state){DataState.Loading->Text("Loading notifications…");DataState.Empty->Text("No notifications yet.");is DataState.Error->{Text(state.message);Button(onRetry){Text("Retry")}};is DataState.Success->LazyColumn{items(state.data,key={it.id}){notification->Card(Modifier.fillMaxWidth().padding(vertical=5.dp).clickable{onRead(notification)},colors=CardDefaults.cardColors(containerColor=if(notification.read_at==null)MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant)){Column(Modifier.padding(16.dp)){Text(icon(notification.type)+" "+notification.title,fontWeight=if(notification.read_at==null)FontWeight.Bold else FontWeight.Normal);Text(notification.body);Text(relative(notification.created_at),style=MaterialTheme.typography.labelSmall)}}}}}}}
private fun icon(type:String)=when(type){"NEW_TENDER_MATCH"->"★";"TENDER_CLOSING_SOON"->"⚠";"TENDER_UPDATED"->"📢";else->"•"}
private fun relative(value:String):String=try{val minutes=java.time.Duration.between(java.time.Instant.parse(value),java.time.Instant.now()).toMinutes();when{minutes<1->"Just now";minutes<60->"$minutes minutes ago";minutes<1440->"${minutes/60} hours ago";else->"${minutes/1440} days ago"}}catch(_:Exception){value.take(10)}
@Composable fun NotificationSettingsScreen(state:DataState<NotificationPreference>,pushConfigured:Boolean,onRetry:()->Unit,onSave:(NotificationPreferenceInput)->Unit){when(state){DataState.Loading->Text("Loading notification settings…",Modifier.padding(24.dp));DataState.Empty->Text("Settings unavailable",Modifier.padding(24.dp));is DataState.Error->Column(Modifier.padding(24.dp)){Text(state.message);Button(onRetry){Text("Retry")}};is DataState.Success->{val p=state.data;var match by remember(p){mutableStateOf(p.new_tender_matches_enabled)};var closing by remember(p){mutableStateOf(p.saved_tender_closing_enabled)};var updates by remember(p){mutableStateOf(p.tender_update_enabled)};var push by remember(p){mutableStateOf(p.push_enabled)};val permission=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){granted->if(!granted)push=false};var email by remember(p){mutableStateOf(p.email_enabled)};var quiet by remember(p){mutableStateOf(p.quiet_hours_enabled)};var start by remember(p){mutableStateOf(p.quiet_hours_start.take(5))};var end by remember(p){mutableStateOf(p.quiet_hours_end.take(5))};Column(Modifier.fillMaxSize().padding(24.dp)){Text("Notifications",style=MaterialTheme.typography.headlineMedium);Text("Get useful tender matches, deadline reminders and amendments. You control each channel before permission is requested.");Toggle("New tender matches",match){match=it};Toggle("Closing reminders",closing){closing=it};Toggle("Tender updates",updates){updates=it};Toggle("Push notifications",push&&pushConfigured){enabled->if(pushConfigured){push=enabled;if(enabled&&Build.VERSION.SDK_INT>=33)permission.launch(Manifest.permission.POST_NOTIFICATIONS)}};if(!pushConfigured)Text("Push client configuration is not installed in this build.",style=MaterialTheme.typography.labelSmall);Toggle("Email notifications",email){email=it};Toggle("Quiet hours",quiet){quiet=it};if(quiet){OutlinedTextField(start,{start=it},label={Text("Start (HH:mm)")});OutlinedTextField(end,{end=it},label={Text("End (HH:mm)")})};Button({onSave(NotificationPreferenceInput(match,closing,updates,email,push&&pushConfigured,true,quiet,"$start:00","$end:00",p.timezone))}){Text("Save settings")}}}}}
@Composable private fun Toggle(label:String,checked:Boolean,onChange:(Boolean)->Unit){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label);Switch(checked,onChange)}}
