package za.co.tenderhub.ui.screens
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import za.co.tenderhub.data.repository.*
import za.co.tenderhub.domain.model.*
class SaveControllerViewModel(private val repo:SavedRepository):ViewModel(){val savedIds=repo.savedIds;val reminderStates=repo.reminderStates;private val _message=MutableStateFlow<String?>(null);val message:StateFlow<String?> =_message
 fun refresh(ids:List<String>)=viewModelScope.launch{repo.refreshStates(ids)}
 fun toggle(id:String,onSuccess:()->Unit={})=viewModelScope.launch{val desired=id !in savedIds.value;when(repo.setSaved(id,desired)){is ApiResult.Success->{_message.value=if(desired)"Tender saved" else "Tender removed";onSuccess()};is ApiResult.Error->_message.value="Couldn't ${if(desired)"save" else "remove"} tender. Check your connection and try again."}}
 fun setReminders(id:String,enabled:Boolean)=viewModelScope.launch{when(repo.setReminders(id,enabled)){is ApiResult.Success->_message.value="Closing reminders ${if(enabled)"enabled" else "disabled"}";is ApiResult.Error->_message.value="Could not update closing reminders."}}
 fun clearMessage(){_message.value=null}}
class SavedTendersViewModel(private val repo:SavedRepository):ViewModel(){private val _state=MutableStateFlow<DataState<SearchResults>>(DataState.Loading);val state:StateFlow<DataState<SearchResults>> =_state;init{load()};fun load(page:Int=1)=viewModelScope.launch{_state.value=DataState.Loading;_state.value=when(val result=repo.list(page)){is ApiResult.Success->if(result.value.items.isEmpty())DataState.Empty else DataState.Success(SearchResults(result.value.items.map{it.tender},result.value.page,result.value.total_pages,savedAt=result.value.items.associate{it.tender.id to it.saved_at}));is ApiResult.Error->DataState.Error(result.message)}};fun loadMore()=viewModelScope.launch{val old=(_state.value as? DataState.Success)?.data?:return@launch;if(old.page>=old.totalPages)return@launch;when(val result=repo.list(old.page+1)){is ApiResult.Success->_state.value=DataState.Success(SearchResults(old.items+result.value.items.map{it.tender},result.value.page,result.value.total_pages,savedAt=old.savedAt+result.value.items.associate{it.tender.id to it.saved_at}));is ApiResult.Error->_state.value=DataState.Error(result.message)}}}
class SavedSearchesViewModel(private val repo:SavedRepository):ViewModel(){private val _state=MutableStateFlow<DataState<List<SavedSearch>>>(DataState.Loading);val state:StateFlow<DataState<List<SavedSearch>>> =_state;fun load()=viewModelScope.launch{_state.value=DataState.Loading;_state.value=when(val r=repo.searches()){is ApiResult.Success->if(r.value.items.isEmpty())DataState.Empty else DataState.Success(r.value.items);is ApiResult.Error->DataState.Error(r.message)}};fun create(name:String,query:String,filters:TenderFilters,sort:String)=viewModelScope.launch{repo.createSearch(SavedSearchInput(name,query,filters.toMap(),sort));load()};fun rename(item:SavedSearch,name:String)=viewModelScope.launch{repo.updateSearch(item.id,SavedSearchInput(name,item.query,item.filters,item.sort,item.alerts_enabled));load()};fun toggleAlerts(item:SavedSearch)=viewModelScope.launch{repo.updateSearch(item.id,SavedSearchInput(item.name,item.query,item.filters,item.sort,!item.alerts_enabled));load()};fun delete(item:SavedSearch)=viewModelScope.launch{repo.deleteSearch(item.id);load()}}
class ProfileViewModel(private val repo:ProfileRepository):ViewModel(){private val _state=MutableStateFlow<DataState<Profile>>(DataState.Loading);val state:StateFlow<DataState<Profile>> =_state;init{load()};fun load()=viewModelScope.launch{_state.value=DataState.Loading;_state.value=when(val r=repo.get()){is ApiResult.Success->DataState.Success(r.value);is ApiResult.Error->DataState.Error(r.message)}};fun update(value:ProfileUpdate)=viewModelScope.launch{_state.value=DataState.Loading;_state.value=when(val r=repo.update(value)){is ApiResult.Success->DataState.Success(r.value);is ApiResult.Error->DataState.Error(r.message)}}}
fun TenderFilters.toMap():Map<String,Any?> = mapOf("provinceId" to provinceId,"districtId" to districtId,"municipalityId" to municipalityId,"category" to category,"tenderType" to tenderType,"organisation" to organisation,"closingFrom" to closingFrom,"closingTo" to closingTo,"issueFrom" to issueFrom,"issueTo" to issueTo,"minValue" to minValue,"maxValue" to maxValue,"status" to status)
fun SavedSearch.toFilters()=TenderFilters(filters["provinceId"] as? String,filters["districtId"] as? String,filters["municipalityId"] as? String,filters["category"] as? String?:"",filters["tenderType"] as? String?:"",filters["organisation"] as? String?:"",filters["closingFrom"] as? String?:"",filters["closingTo"] as? String?:"",filters["issueFrom"] as? String?:"",filters["issueTo"] as? String?:"",filters["minValue"] as? String?:"",filters["maxValue"] as? String?:"",filters["status"] as? String?:"")
