package za.co.tenderhub.ui.screens
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import za.co.tenderhub.ui.navigation.AuthState
@Composable fun SplashScreen(){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator();Text("TenderHub SA",Modifier.padding(top=96.dp),style=MaterialTheme.typography.headlineSmall)}}
@Composable fun WelcomeScreen(onLogin:()->Unit,onSignUp:()->Unit){Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.Center){Text("TenderHub SA",style=MaterialTheme.typography.displaySmall);Spacer(Modifier.height(12.dp));Text("South African tender discovery and procurement intelligence.",style=MaterialTheme.typography.titleMedium);Spacer(Modifier.height(32.dp));Button(onLogin,Modifier.fillMaxWidth()){Text("Log in")};OutlinedButton(onSignUp,Modifier.fillMaxWidth()){Text("Create account")}}}
@Composable fun LoginScreen(state:AuthState,onLogin:(String,String)->Unit,onForgot:()->Unit,onSignUp:()->Unit){var email by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.Center){Text("Welcome back",style=MaterialTheme.typography.headlineLarge);AuthError(state);OutlinedTextField(email,{email=it},label={Text("Email")},modifier=Modifier.fillMaxWidth(),keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Email));OutlinedTextField(password,{password=it},label={Text("Password")},modifier=Modifier.fillMaxWidth(),visualTransformation=PasswordVisualTransformation());Button({onLogin(email,password)},enabled=state !is AuthState.Loading&&email.isNotBlank()&&password.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text("Log in")};TextButton(onForgot){Text("Forgot password?")};TextButton(onSignUp){Text("Create an account")}}}
@Composable fun SignUpScreen(state:AuthState,onSubmit:(String,String,String,String)->Unit){var email by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};var first by remember{mutableStateOf("")};var last by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.Center){Text("Create account",style=MaterialTheme.typography.headlineLarge);AuthError(state);listOf("First name" to first,"Last name" to last,"Email" to email).forEach{(label,value)->OutlinedTextField(value,{when(label){"First name"->first=it;"Last name"->last=it;else->email=it}},label={Text(label)},modifier=Modifier.fillMaxWidth())};OutlinedTextField(password,{password=it},label={Text("Password (10+ characters)")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());Button({onSubmit(email,password,first,last)},enabled=listOf(email,password,first,last).all{it.isNotBlank()},modifier=Modifier.fillMaxWidth()){Text("Sign up")}}}
@Composable private fun AuthError(state:AuthState){if(state is AuthState.Error)Text(state.message,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(vertical=8.dp))}
@Composable fun FeatureScreen(title:String,description:String="NOT IMPLEMENTED — planned for a later phase.",onAccount:(()->Unit)?=null){Column(Modifier.fillMaxSize().padding(24.dp)){Text(title,style=MaterialTheme.typography.headlineLarge);Spacer(Modifier.height(16.dp));Text(description);onAccount?.let{Button(it){Text("Account & settings")}}}}
@Composable fun ForgotScreen(state:za.co.tenderhub.ui.navigation.PasswordResetViewModel.State,onRequest:(String)->Unit,onConfirm:(String,String)->Unit,onLogin:()->Unit){var email by remember{mutableStateOf("")};var token by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.Center){Text("Reset password",style=MaterialTheme.typography.headlineLarge);when(state){za.co.tenderhub.ui.navigation.PasswordResetViewModel.State.Form->{OutlinedTextField(email,{email=it},label={Text("Email")},modifier=Modifier.fillMaxWidth());Button({onRequest(email)},enabled=email.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text("Send reset instructions")}};za.co.tenderhub.ui.navigation.PasswordResetViewModel.State.Loading->CircularProgressIndicator();is za.co.tenderhub.ui.navigation.PasswordResetViewModel.State.Requested->{Text("If an account exists, reset instructions have been sent.");state.developmentToken?.let{developmentToken->LaunchedEffect(developmentToken){if(token.isBlank())token=developmentToken};Text("Development delivery adapter supplied a local reset code.")};OutlinedTextField(token,{token=it},label={Text("Reset code")},modifier=Modifier.fillMaxWidth());OutlinedTextField(password,{password=it},label={Text("New password")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());Button({onConfirm(token,password)},enabled=token.isNotBlank()&&password.length>=10){Text("Reset password")}};za.co.tenderhub.ui.navigation.PasswordResetViewModel.State.Complete->{Text("Your password has been reset.");Button(onLogin){Text("Return to login")}};is za.co.tenderhub.ui.navigation.PasswordResetViewModel.State.Error->{Text(state.message,color=MaterialTheme.colorScheme.error);Button({onRequest(email)}){Text("Retry")}}}}}
@Composable fun AccountScreen(onLogout:()->Unit){Column(Modifier.fillMaxSize().padding(24.dp)){Text("Account & settings",style=MaterialTheme.typography.headlineLarge);Spacer(Modifier.height(16.dp));Text("Your authenticated session is stored securely on this device.");Spacer(Modifier.height(24.dp));Button(onLogout){Text("Log out")};Spacer(Modifier.height(16.dp));Text("Profile editing and other settings: NOT IMPLEMENTED")}}
@Composable fun MainShell(currentRoute:String,onNavigate:(String)->Unit,unreadCount:Int=0,content:@Composable (PaddingValues)->Unit){Scaffold(bottomBar={NavigationBar{listOf("Home" to "home","Search" to "search","Saved" to "saved","Alerts" to "notifications","Profile" to "profile").forEach{(label,route)->NavigationBarItem(selected=currentRoute==route,onClick={onNavigate(route)},icon={Text(label.take(1))},label={Text(if(route=="notifications"&&unreadCount>0)"$label ${unreadCount.coerceAtMost(99)}" else label)})}}},content=content)}
@Composable fun MainFeatureScreen(title:String,currentRoute:String,onNavigate:(String)->Unit,onAccount:(()->Unit)?=null){MainShell(currentRoute,onNavigate,0){padding->Column(Modifier.fillMaxSize().padding(padding).padding(24.dp)){Text(title,style=MaterialTheme.typography.headlineLarge);Spacer(Modifier.height(16.dp));Text("NOT IMPLEMENTED — planned for a later phase.");onAccount?.let{Spacer(Modifier.height(20.dp));Button(it){Text("Account & settings")}}}}}
