package za.co.tenderhub.ui.screens
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.unit.dp
import za.co.tenderhub.domain.model.*
@Composable private fun StateMessage(title:String,button:String?=null,onClick:()->Unit={}){Column(Modifier.fillMaxWidth().padding(32.dp)){Text(title,style=MaterialTheme.typography.bodyLarge);button?.let{Button(onClick){Text(it)}}}}
@Composable fun TenderCardView(t:Tender,onClick:()->Unit){Card(Modifier.fillMaxWidth().padding(vertical=5.dp).clickable(onClick=onClick)){Column(Modifier.padding(16.dp)){Text(t.title,style=MaterialTheme.typography.titleMedium);Text(t.organisation,style=MaterialTheme.typography.bodyMedium);t.reference_number?.let{Text("Reference: $it")};Text(listOfNotNull(t.province,t.category).joinToString(" • "));Text("Closes: ${t.closing_date ?: "Not supplied"}${t.closing_time?.let{" at $it"} ?: ""}",color=MaterialTheme.colorScheme.primary)}}}
@Composable fun HomeDataScreen(state:DataState<HomeResponse>,onRetry:()->Unit,onTender:(String)->Unit){when(state){DataState.Loading->StateMessage("Loading current tenders…");DataState.Empty->StateMessage("No current tenders are available.","Retry",onRetry);is DataState.Error->StateMessage(state.message,"Retry",onRetry);is DataState.Success->LazyColumn(Modifier.fillMaxSize().padding(16.dp)){item{Text("Latest tenders",style=MaterialTheme.typography.headlineMedium)};items(state.data.latest,key={"latest-${it.id}"}){TenderCardView(it){onTender(it.id)}};item{Text("Closing soon",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(top=20.dp))};items(state.data.closing_soon,key={"closing-${it.id}"}){TenderCardView(it){onTender(it.id)}};item{Text("Recently added",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(top=20.dp))};items(state.data.recently_added,key={"recent-${it.id}"}){TenderCardView(it){onTender(it.id)}}}}}
@Composable fun SearchDataScreen(state:DataState<SearchResults>,onSearch:(String,String,String)->Unit,onRetry:()->Unit,onLoadMore:()->Unit,onTender:(String)->Unit){var query by remember{mutableStateOf("")};var category by remember{mutableStateOf("")};var sort by remember{mutableStateOf("relevance")};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Search tenders",style=MaterialTheme.typography.headlineMedium);OutlinedTextField(query,{query=it},label={Text("Keywords")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(category,{category=it},label={Text("Category (optional)")},singleLine=true,modifier=Modifier.fillMaxWidth());Row{listOf("relevance","newest","closing_soon").forEach{value->FilterChip(selected=sort==value,onClick={sort=value},label={Text(value.replace('_',' '))},modifier=Modifier.padding(end=4.dp))}};Button({onSearch(query,category,sort)},Modifier.fillMaxWidth()){Text("Search")};Box(Modifier.weight(1f)){when(state){DataState.Loading->StateMessage("Searching real tender data…");DataState.Empty->StateMessage("No tenders match these filters.");is DataState.Error->StateMessage(state.message,"Retry",onRetry);is DataState.Success->LazyColumn{items(state.data.items,key={it.id}){TenderCardView(it){onTender(it.id)}};if(state.data.page<state.data.totalPages)item{Button(onLoadMore,enabled=!state.data.loadingMore,modifier=Modifier.fillMaxWidth()){Text(if(state.data.loadingMore)"Loading…" else "Load more")}}}}}}}
@Composable fun TenderDetailScreen(state:DataState<TenderDetail>,onRetry:()->Unit){val uri=LocalUriHandler.current;when(state){DataState.Loading->StateMessage("Loading tender details…");DataState.Empty->StateMessage("Tender not found.");is DataState.Error->StateMessage(state.message,"Retry",onRetry);is DataState.Success->{val t=state.data;LazyColumn(Modifier.fillMaxSize().padding(20.dp)){item{Text(t.title,style=MaterialTheme.typography.headlineMedium);Text(t.organisation,style=MaterialTheme.typography.titleMedium);Section("TenderHub normalized information");Field("Reference",t.reference_number);Field("Province",t.province);Field("Municipality",t.municipality);Field("District",t.district);Field("Category",t.category);Field("Tender type",t.tender_type);Field("Issue date",t.issue_date);Field("Closing",listOfNotNull(t.closing_date,t.closing_time).joinToString(" at ").ifBlank{null});Field("Estimated value",t.estimated_value?.let{"${t.currency} ${"%,.2f".format(it)}"});Field("Description",t.description);Field("Contact",listOfNotNull(t.contact_name,t.contact_email,t.contact_phone).joinToString(" • ").ifBlank{null});Section("Source information");Field("Publisher",t.source.name);Field("Source reference",t.source_reference);Field("Ingested",t.ingested_at);Button({uri.openUri(t.source_url)}){Text("View Original Source")};Section("Documents");if(t.documents.isEmpty())Text("No source documents supplied") else t.documents.forEach{TextButton({uri.openUri(it.source_url)}){Text(it.name)}};Section("AI Analysis");Text("NOT IMPLEMENTED")}}}}}
@Composable private fun Section(value:String){Text(value,style=MaterialTheme.typography.titleLarge,modifier=Modifier.padding(top=24.dp,bottom=8.dp))}
@Composable private fun Field(label:String,value:String?){if(!value.isNullOrBlank()){Text(label,style=MaterialTheme.typography.labelMedium);Text(value,modifier=Modifier.padding(bottom=8.dp))}}
