package za.co.tenderhub.ui.screens
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import za.co.tenderhub.domain.model.*
@Composable private fun StateMessage(title:String,button:String?=null,onClick:()->Unit={}){Column(Modifier.fillMaxWidth().padding(32.dp)){Text(title,style=MaterialTheme.typography.bodyLarge);button?.let{Button(onClick){Text(it)}}}}
private fun displayDate(value:String?):String?=try{value?.let{LocalDate.parse(it).format(DateTimeFormatter.ofPattern("d MMMM yyyy"))}}catch(_:Exception){value}
@Composable fun TenderCardView(t:Tender,onClick:()->Unit){Card(Modifier.fillMaxWidth().padding(vertical=6.dp).clickable(onClick=onClick)){Column(Modifier.padding(16.dp)){Text(t.title,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.SemiBold);Spacer(Modifier.height(5.dp));Text(t.organisation);Text(listOfNotNull(t.province,t.municipality).joinToString(" / "));Spacer(Modifier.height(10.dp));Text(if(t.closing_date==null)"Closing date not provided" else "Closing: ${displayDate(t.closing_date)}${t.closing_time?.let{" at ${it.take(5)}"}?:""}",style=MaterialTheme.typography.titleSmall,color=if(t.status=="OPEN")MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error,fontWeight=FontWeight.Bold);t.category?.let{Text("Category: $it")};t.reference_number?.let{Text("Reference: $it")};if(t.status!="OPEN")Text(t.status,color=MaterialTheme.colorScheme.error,fontWeight=FontWeight.Bold)}}}
@Composable fun HomeDataScreen(state:DataState<HomeResponse>,onRetry:()->Unit,onTender:(String)->Unit){when(state){DataState.Loading->StateMessage("Loading current tenders…");DataState.Empty->StateMessage("No current tenders are available.","Retry",onRetry);is DataState.Error->StateMessage(state.message,"Retry",onRetry);is DataState.Success->LazyColumn(Modifier.fillMaxSize().padding(16.dp)){item{Text("Latest tenders",style=MaterialTheme.typography.headlineMedium)};items(state.data.latest,key={"latest-${it.id}"}){TenderCardView(it){onTender(it.id)}};item{Text("Closing soon",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(top=20.dp))};items(state.data.closing_soon,key={"closing-${it.id}"}){TenderCardView(it){onTender(it.id)}};item{Text("Recently added",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(top=20.dp))};items(state.data.recently_added,key={"recent-${it.id}"}){TenderCardView(it){onTender(it.id)}}}}}
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun SearchDataScreen(state:DataState<SearchResults>,filters:TenderFilters,geography:GeographyOptions,onSearch:(String,TenderFilters,String)->Unit,onRetry:()->Unit,onLoadMore:()->Unit,onTender:(String)->Unit){var query by remember{mutableStateOf("")};var sort by remember{mutableStateOf("relevance")};var showFilters by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Search tenders",style=MaterialTheme.typography.headlineMedium);OutlinedTextField(query,{query=it},label={Text("Keywords")},singleLine=true,modifier=Modifier.fillMaxWidth());Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){OutlinedButton({showFilters=true}){Text("Filters${filters.activeCount().takeIf{it>0}?.let{" ($it)"}?:""}")};TextButton({sort=when(sort){"relevance"->"newest";"newest"->"closing_soon";else->"relevance"}}){Text("Sort: ${sort.replace('_',' ')}")}};Button({onSearch(query,filters,sort)},Modifier.fillMaxWidth()){Text("Search")};Box(Modifier.weight(1f)){when(state){DataState.Loading->StateMessage("Searching tenders…");DataState.Empty->StateMessage("No tenders match your search.");is DataState.Error->StateMessage(state.message,"Retry",onRetry);is DataState.Success->LazyColumn{items(state.data.items,key={it.id}){TenderCardView(it){onTender(it.id)}};if(state.data.page<state.data.totalPages)item{Button(onLoadMore,enabled=!state.data.loadingMore,modifier=Modifier.fillMaxWidth()){Text(if(state.data.loadingMore)"Loading…" else "Load more")}}}}}}
 if(showFilters)FilterSheet(filters,geography,onDismiss={showFilters=false}){showFilters=false;onSearch(query,it,sort)}}
@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun FilterSheet(current:TenderFilters,geo:GeographyOptions,onDismiss:()->Unit,onApply:(TenderFilters)->Unit){var draft by remember(current){mutableStateOf(current)};val districts=geo.districts.filter{draft.provinceId==null||it.province_id==draft.provinceId};val municipalities=geo.municipalities.filter{(draft.provinceId==null||it.province_id==draft.provinceId)&&(draft.districtId==null||it.district_id==draft.districtId)};ModalBottomSheet(onDismissRequest=onDismiss){LazyColumn(Modifier.fillMaxWidth().padding(horizontal=20.dp),contentPadding=PaddingValues(bottom=32.dp)){item{Text("Search filters",style=MaterialTheme.typography.headlineSmall);DropdownField("Province",geo.provinces,draft.provinceId,{it.id},{it.name}){draft=draft.copy(provinceId=it,districtId=null,municipalityId=null)};DropdownField("District",districts,draft.districtId,{it.id},{it.name}){draft=draft.copy(districtId=it,municipalityId=null)};DropdownField("Municipality",municipalities,draft.municipalityId,{it.id},{it.name}){draft=draft.copy(municipalityId=it)};FilterText("Category",draft.category){draft=draft.copy(category=it)};FilterText("Tender type",draft.tenderType){draft=draft.copy(tenderType=it)};FilterText("Closing from (YYYY-MM-DD)",draft.closingFrom){draft=draft.copy(closingFrom=it)};FilterText("Closing to (YYYY-MM-DD)",draft.closingTo){draft=draft.copy(closingTo=it)};FilterText("Issue from (YYYY-MM-DD)",draft.issueFrom){draft=draft.copy(issueFrom=it)};FilterText("Issue to (YYYY-MM-DD)",draft.issueTo){draft=draft.copy(issueTo=it)};FilterText("Minimum value",draft.minValue){draft=draft.copy(minValue=it)};FilterText("Maximum value",draft.maxValue){draft=draft.copy(maxValue=it)};DropdownField("Status",listOf("OPEN","CLOSED","CANCELLED","UPCOMING"),draft.status.ifBlank{null},{it},{it}){draft=draft.copy(status=it?:"")};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){TextButton({draft=TenderFilters()}){Text("Clear")};Button({onApply(draft)}){Text("Apply filters")}}}}}}
@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun <T> DropdownField(label:String,items:List<T>,selected:String?,id:(T)->String,name:(T)->String,onSelect:(String?)->Unit){var expanded by remember{mutableStateOf(false)};val display=items.firstOrNull{id(it)==selected}?.let(name)?:"Any";ExposedDropdownMenuBox(expanded,{expanded=it}){OutlinedTextField(display,{},readOnly=true,label={Text(label)},trailingIcon={ExposedDropdownMenuDefaults.TrailingIcon(expanded)},modifier=Modifier.menuAnchor().fillMaxWidth());ExposedDropdownMenu(expanded,{expanded=false}){DropdownMenuItem({Text("Any")},{onSelect(null);expanded=false});items.forEach{item->DropdownMenuItem({Text(name(item))},{onSelect(id(item));expanded=false})}}}}
@Composable private fun FilterText(label:String,value:String,onValue:(String)->Unit){OutlinedTextField(value,onValue,label={Text(label)},singleLine=true,modifier=Modifier.fillMaxWidth())}
@Composable fun TenderDetailScreen(state:DataState<TenderDetail>,onRetry:()->Unit){val uri=LocalUriHandler.current;when(state){DataState.Loading->StateMessage("Loading tender details…");DataState.Empty->StateMessage("Tender not found.");is DataState.Error->StateMessage(state.message,"Retry",onRetry);is DataState.Success->{val t=state.data;LazyColumn(Modifier.fillMaxSize().padding(20.dp)){item{Text(t.title,style=MaterialTheme.typography.headlineMedium);Text(t.organisation,style=MaterialTheme.typography.titleMedium);Section("TenderHub normalized information");Field("Reference",t.reference_number);Field("Province",t.province);Field("Municipality",t.municipality);Field("District",t.district);Field("Category",t.category);Field("Tender type",t.tender_type);Field("Issue date",displayDate(t.issue_date));Field("Closing",if(t.closing_date==null)"Closing date not provided" else "${displayDate(t.closing_date)}${t.closing_time?.let{" at ${it.take(5)}"}?:""}");Field("Status",t.status);Field("Estimated value",t.estimated_value?.let{"${t.currency} ${"%,.2f".format(it)}"});Field("Description",t.description);Field("Contact",listOfNotNull(t.contact_name,t.contact_email,t.contact_phone).joinToString(" • ").ifBlank{null});Section("Source information");Text("TenderHub SA is not the issuing authority.");Field("Publisher",t.source.name);Field("Source reference",t.source_reference);Field("Ingested",t.ingested_at);Button({uri.openUri(t.source_url)}){Text("View Original Source")};Section("Documents");if(t.documents.isEmpty())Text("No source documents supplied") else t.documents.forEach{TextButton({uri.openUri(it.source_url)}){Text(it.name)}};Section("AI Analysis");Text("NOT IMPLEMENTED")}}}}}
@Composable private fun Section(value:String){Text(value,style=MaterialTheme.typography.titleLarge,modifier=Modifier.padding(top=24.dp,bottom=8.dp))}
@Composable private fun Field(label:String,value:String?){if(!value.isNullOrBlank()){Text(label,style=MaterialTheme.typography.labelMedium);Text(value,modifier=Modifier.padding(bottom=8.dp))}}
