package za.co.tenderhub.domain.model
data class User(val id:String,val email:String,val first_name:String,val last_name:String,val phone:String?,val role:String,val status:String)
data class TokenResponse(val access_token:String,val refresh_token:String,val token_type:String,val access_expires_at:String,val refresh_expires_at:String)
data class RegisterRequest(val email:String,val password:String,val first_name:String,val last_name:String,val phone:String?=null)
data class LoginRequest(val email:String,val password:String)
data class RefreshRequest(val refresh_token:String)
data class LogoutRequest(val refresh_token:String?)
data class Tender(val id:String,val source_reference:String,val reference_number:String?,val title:String,val organisation:String,val province:String?,val municipality:String?,val category:String?,val tender_type:String?,val issue_date:String?,val closing_date:String?,val closing_time:String?,val estimated_value:Double?,val currency:String,val status:String,val created_at:String,val ingested_at:String)
data class Page<T>(val items:List<T>,val page:Int,val page_size:Int,val total:Int,val total_pages:Int)
data class HomeResponse(val latest:List<Tender>,val closing_soon:List<Tender>,val recently_added:List<Tender>)
data class Document(val id:String,val name:String,val source_url:String,val mime_type:String?)
data class SourceAttribution(val id:String,val name:String,val organisation:String,val website_url:String)
data class TenderDetail(val id:String,val source_reference:String,val reference_number:String?,val title:String,val description:String?,val organisation:String,val province:String?,val municipality:String?,val district:String?,val category:String?,val subcategory:String?,val tender_type:String?,val issue_date:String?,val closing_date:String?,val closing_time:String?,val estimated_value:Double?,val currency:String,val source_url:String,val status:String,val contact_name:String?,val contact_email:String?,val contact_phone:String?,val ingested_at:String,val documents:List<Document>,val source:SourceAttribution)
data class Province(val id:String,val code:String,val name:String)
data class District(val id:String,val province_id:String,val code:String?,val name:String)
data class Municipality(val id:String,val province_id:String,val district_id:String?,val code:String?,val name:String,val municipality_type:String?,val active:Boolean)
data class PasswordResetRequest(val email:String)
data class PasswordResetRequested(val message:String,val development_token:String?)
data class PasswordResetConfirm(val token:String,val new_password:String)
data class TenderFilters(val provinceId:String?=null,val districtId:String?=null,val municipalityId:String?=null,val category:String="",val tenderType:String="",val organisation:String="",val closingFrom:String="",val closingTo:String="",val issueFrom:String="",val issueTo:String="",val minValue:String="",val maxValue:String="",val status:String=""){
 fun activeCount()=listOf(provinceId,districtId,municipalityId,category.takeIf{it.isNotBlank()},tenderType.takeIf{it.isNotBlank()},organisation.takeIf{it.isNotBlank()},closingFrom.takeIf{it.isNotBlank()},closingTo.takeIf{it.isNotBlank()},issueFrom.takeIf{it.isNotBlank()},issueTo.takeIf{it.isNotBlank()},minValue.takeIf{it.isNotBlank()},maxValue.takeIf{it.isNotBlank()},status.takeIf{it.isNotBlank()}).count{it!=null}
}
data class TenderSavedState(val tender_id:String,val saved:Boolean,val closing_reminders_enabled:Boolean?=null,val reminder_days:List<Int>?=null)
data class TenderIdsRequest(val tender_ids:List<String>)
data class SavedTenderItem(val saved_at:String,val tender:Tender)
data class SavedSearchInput(val name:String,val query:String,val filters:Map<String,Any?>,val sort:String,val alerts_enabled:Boolean=true)
data class SavedSearch(val id:String,val name:String,val query:String,val filters:Map<String,Any?>,val sort:String,val alerts_enabled:Boolean,val created_at:String,val updated_at:String)
data class Profile(val id:String,val email:String,val first_name:String,val last_name:String,val phone:String?,val display_name:String?,val province:String?,val city:String?)
data class ProfileUpdate(val first_name:String,val last_name:String,val phone:String?,val province:String?,val city:String?)
data class NotificationPreference(val id:String,val new_tender_matches_enabled:Boolean,val saved_tender_closing_enabled:Boolean,val tender_update_enabled:Boolean,val email_enabled:Boolean,val push_enabled:Boolean,val in_app_enabled:Boolean,val quiet_hours_enabled:Boolean,val quiet_hours_start:String,val quiet_hours_end:String,val timezone:String,val updated_at:String)
data class NotificationPreferenceInput(val new_tender_matches_enabled:Boolean,val saved_tender_closing_enabled:Boolean,val tender_update_enabled:Boolean,val email_enabled:Boolean,val push_enabled:Boolean,val in_app_enabled:Boolean,val quiet_hours_enabled:Boolean,val quiet_hours_start:String,val quiet_hours_end:String,val timezone:String)
data class TenderNotification(val id:String,val type:String,val title:String,val body:String,val tender_id:String?,val saved_search_id:String?,val priority:String,val read_at:String?,val created_at:String,val expires_at:String?)
data class UnreadCount(val count:Int)
data class PushTokenInput(val token:String,val platform:String="ANDROID",val app_version:String?,val device_identifier:String?=null)
data class PushTokenDelete(val token:String)
data class ReminderInput(val enabled:Boolean,val reminder_days:List<Int> = listOf(7,3,1,0))
data class ReminderState(val tender_id:String,val enabled:Boolean,val reminder_days:List<Int>)
