package za.co.tenderhub.domain.model
data class User(val id:String,val email:String,val first_name:String,val last_name:String,val phone:String?,val role:String,val status:String)
data class TokenResponse(val access_token:String,val refresh_token:String,val token_type:String,val access_expires_at:String,val refresh_expires_at:String)
data class RegisterRequest(val email:String,val password:String,val first_name:String,val last_name:String,val phone:String?=null)
data class LoginRequest(val email:String,val password:String)
data class RefreshRequest(val refresh_token:String)
data class LogoutRequest(val refresh_token:String?)
data class Tender(val id:String,val source_reference:String,val reference_number:String?,val title:String,val organisation:String,val province:String?,val municipality:String?,val category:String?,val tender_type:String?,val issue_date:String?,val closing_date:String?,val closing_time:String?,val estimated_value:Double?,val currency:String,val status:String,val created_at:String,val ingested_at:String)
data class Page<T>(val items:List<T>,val page:Int,val page_size:Int,val total:Int,val total_pages:Int)
data class HomeResponse(val latest:List<Tender>,val closing_soon:List<Tender>,val recently_added:List<Tender>)
data class Document(val id:String,val name:String,val source_url:String,val mime_type:String?)
data class SourceAttribution(val id:String,val name:String,val organisation:String,val website_url:String)
data class TenderDetail(val id:String,val source_reference:String,val reference_number:String?,val title:String,val description:String?,val organisation:String,val province:String?,val municipality:String?,val district:String?,val category:String?,val subcategory:String?,val tender_type:String?,val issue_date:String?,val closing_date:String?,val closing_time:String?,val estimated_value:Double?,val currency:String,val source_url:String,val status:String,val contact_name:String?,val contact_email:String?,val contact_phone:String?,val ingested_at:String,val documents:List<Document>,val source:SourceAttribution)
data class Province(val id:String,val code:String,val name:String)
